# ==============================================================================
# Configuration: bind9_options.conf
# Description: Bind9 Caching Nameserver Setup with Google DNS forwarders
# Author: Maksym Romanov
# ==============================================================================

options {
    directory "/var/cache/bind";

    recursion yes;
    
    # Security enhancement: Allow queries only from localhost and the internal cluster network
    allow-query { localhost; 172.27.27.0/24; };

    forwarders {
        8.8.8.8;
        8.8.4.4;
    };

    dnssec-validation auto;
    listen-on-v6 { any; };
};
