# Rsyslog configuration for forwarding Apache logs to Graylog Server

# Load module for reading local files
$ModLoad imfile

# Access Log Monitoring
$InputFileName /var/log/apache2/access.log
$InputFileTag apache-access:
$InputFileSeverity info
$InputFileFacility local6
$InputRunFileMonitor

# Error Log Monitoring
$InputFileName /var/log/apache2/error.log
$InputFileTag apache-error:
$InputFileSeverity error
$InputFileFacility local6
$InputRunFileMonitor

# Forward all system events and monitored files to centralized Graylog server
*.* @172.27.x.121:1514
