# ==============================================================================
# Configuration: graylog.conf
# Description: Nginx Reverse Proxy for Graylog Web Interface
# Author: Maksym Romanov
# ==============================================================================

server {
    listen 80;
    server_name graylog.____________;

    # Redirect all HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name graylog._____________;

    # SSL Configuration
    ssl_certificate /etc/ssl/certs/graylog-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/graylog-selfsigned.key;

    # Proxy settings to route traffic to the Graylog Web Interface
    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Graylog-Server-URL https://$server_name/;
        
        # Pass traffic to local Graylog instance
        proxy_pass http://127.0.0.1:9000; 
    }
}
